# Generated by Django 4.2.1 on 2023-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_Complete',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
