# Generated by Django 4.2.1 on 2023-05-14 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 15, 5, 44, 437303, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
