# Generated by Django 4.2.1 on 2023-05-14 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 23, 32, 32, 902262, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
