# Generated by Django 4.2.1 on 2023-05-21 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.RenameField(
            model_name='event',
            old_name='is_Complete',
            new_name='is_complete',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
