# Generated by Django 4.2.1 on 2023-05-21 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_day_rename_is_complete_event_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
